export default {
  HEADING: 'Add a new mentor',
  USERNAME_REQ: '* Username is a required property',
  ADD_MENTOR: 'Add Mentor',
  DETAILS: 'Mentor Details',
  NAME: 'Name',
  COURSE: 'Course',
  EARNING: 'Earning',
  PRICE: 'Price',
  OPTIONS: 'Options',
  PENDING_COURSE_REQUEST: 'Pending Course Request',
  APPROVE: 'Approve',
  REJECT: 'Reject',
  DISABLE: 'Disable',
  ALL_COURSES: 'All Courses',
  COURSES: 'Courses',
  MENTOR: 'Mentor',
};
