export default {
  LOGIN_HEADING: 'Welcome Back',
  USERNAME_REQ: '* Username is a required property',
  PASSWORD_REQ: '* Password is a required property',
  NAME_REQ: '* Name is a required property',
  EMAIL_REQ: '* Email is a required property',
  PASSWORD_MATCH: '* Password do not match',
  NO_ACCOUNT: "Don't have a account?",
  SIGN_UP: 'Sign up',
  LOG_IN: 'Log In',
  CREATE_ACCOUNT: 'Create an account',
  NAME: 'Name',
  EMAIL: 'Email',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  REPASSWORD: 'Re-enter password',
  LOGGED_IN: 'Logged in',
  LOG_IN_SUCESS: 'Logged in successfully',
  SIGN_UP_SUCESS: 'Signed up successfully',
  SIGN_UP_FAILED: 'Signing failed',
  INVALID_CREDENTIALS: 'Please enter valid credentials',
  HEAD_TO_LOG_IN: 'Please log in',
};
