export default {
  COURSE_NOT_AVAILABLE: 'Now course is not available for purchase',
  COURSE_AVAILABLE: 'Now course is available for purchase',
  COURSE_APPROED: 'Course approved successfully',
  COURSE_REJECTED: 'Course rejected successfully',
  ERROR_REJECTING: 'There was an error rejecting the course',
  TRY_AGAIN: 'Please try again later',
  ADD_NEW_COURSE: 'Now he can also add courses',
  NO_USER_EXISTS: 'No such user exists.',
  ANOTHER_USERNAME: 'Please enter another username',
  ERROR_OCCURRED: 'There was an error',
  SUCCESS: 'Success!',
  CANNOT_ADD_FB: 'You cannot add feedback to this course',
  PURCHASE_ADD_FB: 'Please purchase the course to add feedback.',
  APPROVAL_REQUEST: 'Course approval request sent to admin.',
  ADMIN_TO_APPROVE: 'Please wait for the admin to approve the course',
  NOT_ALLOWED_TO_ADD_COURSE: 'You are not allowed to add a course',
  ASK_MENTOR: 'Please ask mentor to do this.',
  ANOTHER_COURSE: 'Another course with the same name already exists.',
  ADD_ANOTHER_COURSE: 'Please add a course with different name',
  VISIT_MY_LEARNING: 'Visit my learning section to access the course',
};
