export default {
  HEADING: 'My Earnings',
  NO_COURSE:
    "Your haven't made any course till now, please add a course to earn.",
  NAME: 'Name',
  COURSE: 'Course',
  REMOVE: 'Remove',
  EARNING: 'Earning',
  SUBMIT: 'Submit',
  ADD_COURSE: 'Add a new course',
  ADD_FAQ: 'Add Faq',
  COURSE_DETAILS: 'Course Details',
  COURSE_NAME_REQ: '* Course name is a required property',
  COURSE_PRICE_REQ: '* Price is a required property',
  COURSE_DURATION_REQ: '* Duration is a required property',
  VIDEO_LINK_REQ: '* Video Link is a required property',
  QUESTION_REQ: '* Question is a required property',
  ANSWER_REQ: '* Answer is a required property',
  PRICE: 'Price',
  DURATION: 'Duration',
  VIDEO: 'Video Link',
  FAQ_HEADING: 'FAQ Details',
  COURSE_NAME: 'Course name',
};
