export default {
  LOGIN_HEADING: 'Welcome Back',
  USERNAME_REQ: '* Username is a required property',
  PASSWORD_REQ: '* Password is a required property',
  NAME_REQ: '* Name is a required property',
  EMAIL_REQ: '* Email is a required property',
  PASSWORD_MATCH: '* Password do not match',
  NO_ACCOUNT: "Don't have a account?",
  SIGN_UP: 'Sign up',
  LOG_IN: 'Log In',
  CREATE_ACCOUNT: 'Create an account',
  NAME: 'Name',
  EMAIL: 'Email',
  USERNAME: 'Username',
  PASSWORD: 'Password',
  REPASSWORD: 'Re-enter password',
};
